[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
catwifview = "8rJgztGCgqNxHvXNC8LW6AazQhERP9zCuBMRUKkh2MDx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/soldev/.config/solana/id.json"

[test]
startup_wait = 40000
shutdown_wait = 2000
upgradeable = false

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.test.ts"
