[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
catwifview = "8KZJqXCybjMKC4NB5g7FsLPNGvNrvtzKD8sk9fUuV5wZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/soldev/.config/solana/id.json"

[test]
startup_wait = 30000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.test.ts"
